#!/usr/bin/env python3
"""
E8-Core: Correct Lattice-Based Encryption using E8^N Direct Sum

Mathematical Foundation:
- E8 lattice: densest packing in 8D, 240 roots, Weyl group ~696M
- E8^N: direct sum of N copies, dimension = 8N
- Security: Closest Vector Problem (CVP) with bad basis is believed hard
- This is a correct implementation of the GGH encryption framework over E8^N

WARNING: This is a DEMONSTRATION. Real post-quantum security requires:
- Dimension >= 512 (N >= 64)
- NIST-vetted schemes (Kyber, Dilithium) for production use
- Extensive cryptanalysis

Author: Chain-Breaker Team / Hive Reconstruction
Version: 2.0.0
"""

import numpy as np
import hashlib
import struct
import sys
import os
from typing import List, Tuple, Optional, Union

__version__ = "2.0.0"
__all__ = ['E8Lattice', 'E8Cipher', 'E8WeylTransform', 'generate_unimodular']

# =============================================================================
# CONSTANTS
# =============================================================================

# Standard orthogonal E8 basis (8 vectors, each length sqrt(2))
# These generate the D8 sublattice, which sits inside E8.
# The full E8 lattice is D8 union (D8 + (1/2,...,1/2)).
# For cryptographic purposes, using D8 as the atomic cell is sufficient
# because scaling by S gives S*D8, and S*D8 is still a hard lattice.
E8_BASIS_ORTHOGONAL = np.array([
    [ 1,  1,  0,  0,  0,  0,  0,  0],
    [ 1, -1,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  1,  1,  0,  0,  0,  0],
    [ 0,  0,  1, -1,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  1,  1,  0,  0],
    [ 0,  0,  0,  0,  1, -1,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  1,  1],
    [ 0,  0,  0,  0,  0,  0,  1, -1],
], dtype=np.float64)

E8_BASIS_INVERSE = E8_BASIS_ORTHOGONAL.T / 2.0  # Since G @ G.T = 2*I

# Lattice parameters
DEFAULT_N = 16                # Number of E8 blocks (dimension = 8*N = 128)
DEFAULT_SCALE = 1200.0        # Lattice spacing S (must be > 722 for arbitrary bytes)
DEFAULT_NOISE_SIGMA = 0.05    # Gaussian noise std dev
DEFAULT_R_BOUND = 100         # Random coefficient bound for lattice point


def generate_unimodular(n: int, operations: int = 200, max_multiplier: int = 5,
                        seed: Optional[int] = None) -> np.ndarray:
    """
    Generate a random unimodular integer matrix via elementary row operations.

    A unimodular matrix has determinant ±1 and integer entries.
    It generates the same lattice as the identity, but with a
    "bad" (long, non-orthogonal) basis.

    Args:
        n: Matrix dimension
        operations: Number of elementary ops to apply
        max_multiplier: Max |k| for "add k*row_j to row_i"
        seed: Random seed for reproducibility

    Returns:
        np.ndarray: n×n unimodular integer matrix
    """
    if seed is not None:
        np.random.seed(seed % (2**32))

    U = np.eye(n, dtype=np.int64)

    for _ in range(operations):
        op_type = np.random.randint(0, 3)
        if op_type == 0:
            # Type 1: Add k * row_j to row_i
            i, j = np.random.choice(n, 2, replace=False)
            k = np.random.randint(-max_multiplier, max_multiplier + 1)
            if k == 0:
                continue
            U[i] += k * U[j]
        elif op_type == 1:
            # Type 2: Swap two rows
            i, j = np.random.choice(n, 2, replace=False)
            U[[i, j]] = U[[j, i]]
        else:
            # Type 3: Multiply a row by -1
            i = np.random.randint(n)
            U[i] *= -1

    return U.astype(np.float64)


class E8Lattice:
    """
    E8^N lattice: direct sum of N copies of the E8 root lattice.

    This is the mathematical foundation for the cipher.
    The lattice is generated by a block-diagonal orthogonal basis,
    scaled by factor S.

    Attributes:
        N (int): Number of E8 blocks
        dim (int): Total dimension = 8 * N
        scale (float): Lattice spacing S
        good_basis (np.ndarray): Private short basis, shape (dim, dim)
        public_basis (np.ndarray): Public bad basis, shape (dim, dim)
        basis_inverse (np.ndarray): Inverse of good_basis for decoding
        min_gs_length (float): Length of shortest Gram-Schmidt vector
    """

    def __init__(self, N: int = DEFAULT_N, scale: float = DEFAULT_SCALE,
                 public_basis: Optional[np.ndarray] = None,
                 unimodular: Optional[np.ndarray] = None):
        """
        Initialize E8^N lattice.

        Args:
            N: Number of E8 blocks
            scale: Lattice spacing S
            public_basis: Pre-computed public basis (optional)
            unimodular: Pre-computed unimodular matrix (optional)
        """
        self.N = N
        self.dim = 8 * N
        self.scale = float(scale)

        # Build good basis: block-diagonal with N copies of scale * E8_BASIS_ORTHOGONAL
        self.good_basis = np.zeros((self.dim, self.dim), dtype=np.float64)
        for i in range(N):
            start = 8 * i
            self.good_basis[start:start+8, start:start+8] = scale * E8_BASIS_ORTHOGONAL

        # Inverse for coordinate extraction
        self.basis_inverse = np.zeros((self.dim, self.dim), dtype=np.float64)
        for i in range(N):
            start = 8 * i
            self.basis_inverse[start:start+8, start:start+8] = E8_BASIS_INVERSE / scale

        # Build or use public basis
        if public_basis is not None:
            self.public_basis = public_basis.astype(np.float64)
            self.unimodular = unimodular.astype(np.float64) if unimodular is not None else None
        else:
            # Generate random unimodular transformation
            self.unimodular = generate_unimodular(self.dim, operations=200, max_multiplier=5)
            self.public_basis = self.unimodular @ self.good_basis

        # Compute min Gram-Schmidt length (for decoding radius)
        # For our orthogonal block-diagonal basis, all GS vectors have length scale * sqrt(2)
        self.min_gs_length = scale * np.sqrt(2.0)

    def babai_nearest_plane(self, target: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """
        Babai's nearest plane algorithm for our orthogonal block-diagonal basis.

        Since the good basis is block-orthogonal, this reduces to:
        1. Extract coordinates in each block using the inverse basis
        2. Round coordinates to nearest integers
        3. Reconstruct lattice point

        Args:
            target: Point in R^dim

        Returns:
            lattice_point: Nearest lattice point
            coefficients: Integer coefficients in good basis
        """
        target = target.astype(np.float64)

        # Extract raw coefficients: target @ basis_inverse
        # Since basis_inverse is the right inverse of good_basis (for row-convention),
        # we use matrix multiplication directly, NOT transposed.
        coeffs_raw = target @ self.basis_inverse
        coeffs = np.rint(coeffs_raw).astype(np.int64)

        # Reconstruct lattice point: coeffs @ good_basis
        lattice_point = coeffs.astype(np.float64) @ self.good_basis

        return lattice_point, coeffs

    def encode_bytes(self, data: bytes) -> np.ndarray:
        """Convert bytes to perturbation vector in R^dim."""
        padded = data + b'\x00' * ((self.dim - len(data) % self.dim) % self.dim)
        return np.array(list(padded), dtype=np.float64)

    def decode_bytes(self, vector: np.ndarray, original_len: int) -> bytes:
        """Convert perturbation vector back to bytes."""
        clamped = np.clip(np.rint(vector), 0, 255).astype(np.uint8)
        return bytes(clamped[:original_len])

    def hash_to_point(self, data: bytes) -> np.ndarray:
        """Deterministically hash data to a point in E8^N space."""
        hash_bytes = hashlib.sha256(data).digest()
        # Extend to dim bytes via recursive hashing if needed
        extended = hash_bytes
        while len(extended) < self.dim:
            extended += hashlib.sha256(extended).digest()
        coords = np.array(list(extended[:self.dim]), dtype=np.float64) / 256.0
        return coords

    def weyl_reflection(self, point: np.ndarray, root_idx: int) -> np.ndarray:
        """Apply Weyl reflection across a root hyperplane."""
        # For E8^N, we work with one block at a time
        block = root_idx // 240
        if block >= self.N:
            raise IndexError(f"root_idx exceeds available roots in E8^{self.N}")

        # Use first block's roots for simplicity (all blocks are isomorphic)
        root = E8_BASIS_ORTHOGONAL[root_idx % 8].astype(np.float64)  # Simplified
        point_block = point[8*block:8*(block+1)]

        dot = np.dot(point_block, root)
        norm_sq = np.dot(root, root)
        reflected = point_block - 2.0 * dot / norm_sq * root

        result = point.copy()
        result[8*block:8*(block+1)] = reflected
        return result

    def lattice_distance(self, p1: np.ndarray, p2: np.ndarray) -> float:
        """Euclidean distance in E8^N space."""
        return float(np.linalg.norm(p1 - p2))


class E8Cipher:
    """
    E8^N-based encryption following the GGH framework.

    Security Model:
    - Private key: good_basis (short, orthogonal)
    - Public key: public_basis = U @ good_basis (bad, long)
    - Encryption: c = r @ public_basis + m + e
    - Decryption: Babai nearest plane finds r @ public_basis, subtract to get m+e

    The hardness comes from the Closest Vector Problem (CVP):
    finding the nearest lattice point to c using only the public basis
    is computationally hard in high dimensions.

    Attributes:
        lattice (E8Lattice): The E8^N lattice
        N (int): Number of E8 blocks
        dim (int): Total dimension
        block_size (int): Bytes per block (= dim)
    """

    def __init__(self, private_seed: Optional[bytes] = None,
                 N: int = DEFAULT_N, scale: float = DEFAULT_SCALE):
        """
        Initialize cipher.

        Args:
            private_seed: Seed for deterministic key generation
            N: Number of E8 blocks
            scale: Lattice spacing
        """
        self.N = N
        self.dim = 8 * N
        self.block_size = self.dim  # One byte per dimension

        if private_seed is None:
            private_seed = os.urandom(32)
        self.private_seed = private_seed

        # Deterministic key generation from seed
        seed_int = int.from_bytes(private_seed[:8], 'big') % (2**32)
        np.random.seed(seed_int)

        # Generate lattice with deterministic unimodular transform
        uni = generate_unimodular(self.dim, operations=200, max_multiplier=5, seed=seed_int)
        self.lattice = E8Lattice(N=N, scale=scale, unimodular=uni)

    def encrypt(self, plaintext: bytes) -> dict:
        """
        Encrypt plaintext using E8^N lattice.

        Args:
            plaintext: Data to encrypt

        Returns:
            dict: {
                'ciphertext': List of float64 arrays (one per block),
                'nonce': Hex nonce,
                'params': {'N': ..., 'scale': ..., 'dim': ...}
            }
        """
        # Pad to multiple of block_size
        pad_len = (self.block_size - len(plaintext) % self.block_size) % self.block_size
        padded = plaintext + bytes(pad_len)

        ciphertext_blocks = []
        np.random.seed(int.from_bytes(self.private_seed[:4], 'big') % (2**32))

        for i in range(0, len(padded), self.block_size):
            block = padded[i:i+self.block_size]
            m = self.lattice.encode_bytes(block)

            # Random lattice point: r @ public_basis
            r = np.random.randint(-DEFAULT_R_BOUND, DEFAULT_R_BOUND + 1, size=self.dim)
            lattice_pt = r.astype(np.float64) @ self.lattice.public_basis

            # Small Gaussian noise
            e = np.random.normal(0, DEFAULT_NOISE_SIGMA, self.dim)

            # Ciphertext: lattice point + message perturbation + noise
            c = lattice_pt + m + e
            ciphertext_blocks.append(c)

        return {
            'ciphertext': [c.tolist() for c in ciphertext_blocks],
            'nonce': self.private_seed.hex()[:16],
            'pad_len': pad_len,
            'params': {
                'N': self.N,
                'scale': self.lattice.scale,
                'dim': self.dim,
                'version': __version__
            }
        }

    def decrypt(self, encrypted_data: dict) -> bytes:
        """
        Decrypt ciphertext using private good basis.

        Args:
            encrypted_data: Result from encrypt()

        Returns:
            bytes: Decrypted plaintext
        """
        ciphertext_blocks = encrypted_data['ciphertext']
        pad_len = encrypted_data.get('pad_len', 0)

        plaintext = bytearray()

        for c_list in ciphertext_blocks:
            c = np.array(c_list, dtype=np.float64)

            # Find nearest lattice point using good basis (private key operation)
            lattice_pt, _ = self.lattice.babai_nearest_plane(c)

            # Recover perturbation: c - lattice_pt = m + e
            perturbation = c - lattice_pt

            # Round to nearest byte (noise is small enough)
            block_bytes = self.lattice.decode_bytes(perturbation, self.block_size)
            plaintext.extend(block_bytes)

        # Remove padding
        if pad_len > 0:
            plaintext = plaintext[:-pad_len]

        return bytes(plaintext)

    def get_public_key(self) -> dict:
        """Export public key for sharing."""
        return {
            'public_basis': self.lattice.public_basis.tolist(),
            'N': self.N,
            'scale': self.lattice.scale,
            'dim': self.dim
        }

    def get_private_key(self) -> dict:
        """Export private key (keep secret!)."""
        return {
            'private_seed': self.private_seed.hex(),
            'good_basis': self.lattice.good_basis.tolist(),
            'unimodular': self.lattice.unimodular.tolist() if self.lattice.unimodular is not None else None,
            'N': self.N,
            'scale': self.lattice.scale
        }


class E8WeylTransform:
    """
    Deterministic Weyl transformation for hashing/blockchain.

    Uses E8 symmetries to create a hash-like function.
    This is NOT encryption but a mixing primitive.
    """

    def __init__(self, N: int = DEFAULT_N):
        self.lattice = E8Lattice(N=N)

    def transform(self, data: bytes, seed: int) -> bytes:
        """Apply deterministic Weyl transformation to data."""
        point = self.lattice.hash_to_point(data)
        np.random.seed(seed % (2**32))
        num_reflections = np.random.randint(5, 15)

        result = point.copy()
        for _ in range(num_reflections):
            root_idx = np.random.randint(0, 240)
            result = self.lattice.weyl_reflection(result, root_idx)

        return hashlib.sha256(result.tobytes()).digest()


# =============================================================================
# SELF-TEST SUITE
# =============================================================================

def run_self_tests():
    """Run comprehensive self-tests for E8-Core v2."""
    print("=" * 70)
    print("🧪 E8-Core Self-Test Suite v2.0")
    print("=" * 70)

    tests_passed = 0
    tests_failed = 0

    # Test 1: Unimodular generation
    print("\n1️⃣ Testing Unimodular Matrix Generation...")
    try:
        U = generate_unimodular(16, operations=100, max_multiplier=3, seed=42)
        det = round(np.linalg.det(U))
        assert det in [-1, 1], f"det={det}, expected ±1"
        assert U.dtype == np.float64
        print(f"   ✅ det(U) = {det}")
        print(f"   📊 Shape: {U.shape}, Entry range: [{U.min():.1f}, {U.max():.1f}]")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Test 2: E8 Lattice Initialization
    print("\n2️⃣ Testing E8^N Lattice Initialization...")
    try:
        lat = E8Lattice(N=4, scale=DEFAULT_SCALE)
        assert lat.dim == 32, f"Expected dim=32, got {lat.dim}"
        assert lat.good_basis.shape == (32, 32)
        assert lat.public_basis.shape == (32, 32)
        print(f"   ✅ Lattice: E8^{lat.N}, dim={lat.dim}")
        print(f"   📊 Good basis cond: {np.linalg.cond(lat.good_basis):.2f}")
        print(f"   📊 Public basis cond: {np.linalg.cond(lat.public_basis):.2f}")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Test 3: Babai Nearest Plane
    print("\n3️⃣ Testing Babai Nearest Plane...")
    try:
        lat = E8Lattice(N=4, scale=DEFAULT_SCALE)
        # Create a known lattice point plus small perturbation
        true_coeffs = np.array([1, -2, 3, 0] * 8, dtype=np.int64)
        lattice_pt = true_coeffs.astype(np.float64) @ lat.good_basis
        noise = np.random.normal(0, 0.01, lat.dim)
        target = lattice_pt + noise

        recovered_pt, recovered_coeffs = lat.babai_nearest_plane(target)
        assert np.allclose(recovered_coeffs, true_coeffs), "Babai recovered wrong coeffs!"
        assert np.allclose(recovered_pt, lattice_pt), "Babai recovered wrong point!"
        print("   ✅ Babai correctly recovered lattice point")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Test 4: E8 Cipher Encrypt/Decrypt
    print("\n4️⃣ Testing E8 Cipher Round-Trip...")
    try:
        cipher = E8Cipher(private_seed=b'test-seed-32-bytes-long!!!', N=4, scale=DEFAULT_SCALE)
        messages = [
            b"Hello E8",
            b"A" * 31,
            b"Binary\x00\xff\x80data",
            b"x" * 64,
        ]
        for msg in messages:
            encrypted = cipher.encrypt(msg)
            decrypted = cipher.decrypt(encrypted)
            assert decrypted == msg, f"Round-trip failed: {decrypted!r} != {msg!r}"
        print(f"   ✅ All {len(messages)} round-trip tests passed")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Test 5: Larger dimension test
    print("\n5️⃣ Testing Larger Dimension (N=8, 64D)...")
    try:
        cipher = E8Cipher(private_seed=b'another-seed-32-bytes!!', N=8, scale=DEFAULT_SCALE)
        msg = b"The quick brown fox jumps over the lazy dog. " * 2  # 88 bytes
        encrypted = cipher.encrypt(msg)
        decrypted = cipher.decrypt(encrypted)
        assert decrypted == msg, "Large dimension round-trip failed"
        print(f"   ✅ N=8 round-trip passed ({len(msg)} bytes)")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Test 6: Determinism
    print("\n6️⃣ Testing Deterministic Key Generation...")
    try:
        c1 = E8Cipher(private_seed=b'deterministic-test-key!!!', N=4, scale=DEFAULT_SCALE)
        c2 = E8Cipher(private_seed=b'deterministic-test-key!!!', N=4, scale=DEFAULT_SCALE)
        assert np.allclose(c1.lattice.public_basis, c2.lattice.public_basis)
        msg = b"determinism check"
        e1 = c1.encrypt(msg)
        e2 = c2.encrypt(msg)
        # Note: encryption is NOT deterministic due to random r and noise,
        # but decryption should work from both
        d1 = c1.decrypt(e2)
        d2 = c2.decrypt(e1)
        assert d1 == msg and d2 == msg
        print("   ✅ Deterministic keys, cross-decrypt works")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Test 7: Weyl Transform
    print("\n7️⃣ Testing E8WeylTransform...")
    try:
        weyl = E8WeylTransform(N=4)
        result1 = weyl.transform(b"test data", seed=12345)
        result2 = weyl.transform(b"test data", seed=12345)
        assert result1 == result2, "Weyl transform not deterministic"
        assert len(result1) == 32
        print(f"   ✅ Weyl hash: {result1.hex()[:40]}...")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Test 8: Public/Private key export
    print("\n8️⃣ Testing Key Export...")
    try:
        cipher = E8Cipher(private_seed=b'key-export-test-32-by!!', N=4, scale=100.0)
        pk = cipher.get_public_key()
        sk = cipher.get_private_key()
        assert 'public_basis' in pk
        assert 'good_basis' in sk
        print("   ✅ Key export works")
        tests_passed += 1
    except Exception as e:
        print(f"   ❌ FAILED: {e}")
        tests_failed += 1

    # Summary
    print()
    print("=" * 70)
    print("📊 TEST SUMMARY")
    print("=" * 70)
    print(f"   ✅ Passed: {tests_passed}")
    print(f"   ❌ Failed: {tests_failed}")
    print(f"   📈 Success Rate: {tests_passed}/{tests_passed + tests_failed}")

    if tests_failed == 0:
        print("\n🎉 ALL TESTS PASSED!")
        print("=" * 70)
        return 0
    else:
        print(f"\n⚠️ {tests_failed} test(s) failed")
        print("=" * 70)
        return 1


if __name__ == "__main__":
    exit_code = run_self_tests()
    sys.exit(exit_code)
